In [18]:
import pandas as pd

#读取数据--> read_csv
#usecols：规定需要读取的列
df=pd.read_csv('csv_data/01.csv',usecols=['年龄','性别','爱好'])

#数据处理
df['工作']='AI应用工程师'
df['日期']='2026/11/12'
df

#写入数据--> to_csv --- index=False：不写入索引列
df.to_csv('csv_data/02.csv',index=False)

In [19]:
#数据查看，选择及过滤

#配置项，展示所有数据
pd.set_option('display.max_rows',None)

df.head() #查看前n行数据
df.tail() #查看结尾n行数据
df.describe() #数值列的统计描述
df.info() #查看数据信息（列名，非空计数，数据类型）
df.shape #属性，查看数据维度（行数，列数）
df.columns #属性，查看列名

#df['列名'] /df.列名：操作单列
#df[['列1','列2']]：操作多列
#df.iloc[start:stop:step]：基于行号完成切片（不含stop）
#df.loc[start:stop:step]：基于索引标签完成切片(含stop)

#单条件：df[df['销售数量'>=10]]
#单条件：df[df['产品类别'].isin['服装','食品']]
#单条件：df[df['单价'].between(50,200)]-->默认包含边界（inclusive=""）
#多条件：&（并且），|（或）

<class 'pandas.DataFrame'>
RangeIndex: 1 entries, 0 to 0
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   年龄      1 non-null      int64
 1   性别      1 non-null      str
 2   爱好      1 non-null      str
 3   工作      1 non-null      str
 4   日期      1 non-null      str
dtypes: int64(1), str(4)
memory usage: 172.0 bytes

Index(['年龄', '性别', '爱好', '工作', '日期'], dtype='str')

In [20]:
#数据清洗：是指发现并纠正数据中可识别的错误的过程，包括处理缺失值，重复值，异常值，统一数据格式，保证数据的一致性

pd.set_option('display.min_rows',30) #设置显示行数，表现为前面一半，后面一半，中间折叠（默认十行）

#1.读取数据
df=pd.read_csv('csv_data/02.csv')

#2.数据清洗
#2.1缺失值处理
df.isnull() #查看缺失值

#2.1.1删除缺失值
df.dropna() #删除缺失值所在行
df.dropna(axis=1) #axis值设为1，表示删除所在列，默认为0默认删除行
df

#2.1.2填充缺失值
df.fillna('---') #填充缺失值
df.ffill() #填充缺失值，填充上一行的数据
df.bfill() #填充缺失值，填充下一行的数据

   年龄 性别    爱好       工作          日期
0  18  男  Java  AI应用工程师  2026/11/12

In [21]:
#2.2 重复值处理
#2.2.1 查看重复值
df.duplicated() #查看重复值（所有列的数据都一样）
df.duplicated(subset=['工作']) #subset指定列的数据重复

#2.2.2 删除重复值-->drop_duplicates
df.drop_duplicates(subset=['工作'],keep='first') #keep：保留重复值的第一行或者最后一行，False表示为全部删除

   年龄 性别    爱好       工作          日期
0  18  男  Java  AI应用工程师  2026/11/12

In [22]:
#2.3 异常值的处理
#2.3.1查看异常值
df[df['年龄']<18]

#2.3.2 删除异常值
df.drop(df[df['年龄']<18].index)

#2.3.3 修复异常值
df['年龄']=df['年龄'].abs() #绝对值
df

   年龄 性别    爱好       工作          日期
0  18  男  Java  AI应用工程师  2026/11/12

In [24]:
#2.4 数据格式处理
df['日期']=df['日期'].str.replace('/','-')
df

   年龄 性别    爱好       工作          日期
0  18  男  Java  AI应用工程师  2026-11-12